### ISSUE TITLE
Add README.md or Makefile or something

### ISSUE THREAD

**Issue by JJ** [raiben/tropes_open_data#1]
To indicate the tools needed to make everything work and compile it.

**Comment by rhgarcia** [comment]
Hi, 
I have allowed the use of "invoke" with the tasks.py because it is more "pythonic" than a makefile in my opinion (although both are valid approaches and people use them). 
Now it is as easy as doing "invoke clean build open-pdf" to perform all the actions.
However, I didn't include a good way to handle the requirements so that's something to improve :-)

**Comment by JJ** [comment]
You need to add some instructions on how to use invoke. I really have no idea... Also refer to this issue when you change the README.md

**Comment by Beelzenef** [comment]
It would be nice to know what is the project about thanks to the README, I'm interested in storytelling and tropes, but can't say exactly if that's the topic you are working with 👍

**Comment by JJ** [comment]
@Beelzenef totally right. @raiben , can you help?

**Comment by rhgarcia** [comment]
I will !! :-)

**Comment by JJ** [comment]
:loudspeaker:

**Comment by rhgarcia** [comment]
Hi @Beelzenef ,
A promise made is a debt unpaid. I have modified the readme and I hope that it is clearer now :-)

Thank you!!!!
